# Can You Rescue Your Crew? (1) Express (2023.04.07)

link: https://fivethirtyeight.com/features/can-you-rescue-your-crew/

## I. Puzzle

or Easter, you and your family decide to decorate 10 beautiful eggs. You pull a fresh carton of eggs out of your fridge and remove 10 eggs. There are two eggs remaining in the carton, which you return to the fridge.

The next day, you open the carton again to find that the positions of the eggs have somehow changed — or so you think. Perhaps the Easter Bunny was snooping around your fridge?

The 12 slots in the carton are arranged in a six-by-two array that is symmetric upon a 180-degree rotation, and the eggs are indistinguishable from each other. How many distinct ways are there to place two eggs in this carton? (Note: Putting two eggs in the two leftmost slots should be considered the same as putting them in the two rightmost slots, since you can switch between these arrangements with a 180-degree rotation of the carton.)

## II. Solution

We first analyse the question without the rotation. If you put 2 indistinguishable eggs into $n$ slots there are 

$$X=\binom{n}{2}= \frac{n(n-1)}{2}$$ 

possibilities.

Taking the rotation into account, two cases have to be considered. The first case are positions where a 180° rotation results in a different position. Therefore, theses cases are double counted. The second case are positions where a 180° rotation does not change the position and hence, we do not need to correct for double counting. To count the positions from the second case, the position must be symmetrical to the centre:  The eggs have to be in different rows and on different (horizontal) sides of the centre. The distance of the column to the centre must to be the same. Hence, the number of positions from the secons case are equal to the number of slots left or right to the centre: $n/2$. 

$$X=\frac{n(n-1)-n}{2\cdot2}+\frac{n}{2}=\frac{n^2}{4}$$

For a carton with 12 slots there are 36 positions.

### III. Check the result

In [4]:
import numpy as np

In [2]:
rows = 2
columns = 6
eggs = 2

comb = list()
carton = np.zeros(rows*columns)

for egg_1 in range(rows*columns):
	for egg_2 in range(egg_1+1, rows*columns):
		c = carton.copy()
		c[egg_1] = 1
		c[egg_2] = 1
		
		c = c.reshape(rows, columns)
		comb.append(c)
		
solutions = list() 

for arr in comb:
    if not any(np.array_equal(arr, i) for i in solutions):
        arr_rotation = np.flip(arr)
        if not any(np.array_equal(arr_rotation, i) for i in solutions):
        	solutions.append(arr)
        
for s in solutions:
	print(f'{s}\n')

print(f'Solution: {len(solutions)}')

[[1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

[[0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 